<!--Main layout-->
<main>
    <div class="container">

      <!--Section: Main info-->
      <section class="mt-1 pt-1 wow">
      <div class="row">
  <div class="col-md-12 col-xl-10 col-sm-12 mb-1 mt-1">
    
    <div class="card">
    <div class="card-header info">
    Term & Condition
  </div>
  <div class="card-body">
  
  <p>This FNI Distributor Agreement shall be deemed to be effective and valid from the date of confirmation of an applicant as FNI Distributor of FNIONLINE MARKETING PRIVATE LIMITED (&lsquo;FNI&rsquo;) Pursuant to execution of the FNI Distributor Form ('Form'), by FNI, which shall be deemed to be incorporated hereunder.</p>
<p>By successfully executing the Form, you hereby agree to be bound by the terms and conditions of this Agreement and give your irrevocable consent to the process of selling the products of FNI in the manner stipulated herein, and any appropriate changes that may be made to the terms and conditions of this Agreement by FNI, including due to any legal or regulatory requirement, business exigencies, instructions from any judicial or a quasi-judicial body or due to any natural calamity beyond the reasonable control of FNI, its partners and associates or for any other reason.</p>
<p>For the purposes of this Agreement, the term &lsquo;you&rsquo; and wherever the context so requires &lsquo;your&rsquo; shall mean any natural or legal person who is a FNIDistributor. The term Person includes any resident individual, sole proprietorship, unincorporated association, unincorporated organization, body corporate, corporation, company, partnership, limited liability company, limited liability partnership, joint venture or any other resident entity or organization. It is herein clarified that this Agreement shall stand automatically terminated in the event of termination of the partnership deed of FNI Distributor, if such FNI Distributor is registered as a partnership firm with FNI. Additionally, in the event of any change in the constitution of a partnership firm registered as an FNI Distributor, this Agreement and the Account (defined below) of such FNI Distributor on the Website shall be automatically terminated, unless expressly permitted otherwise by FNI Distributor.</p>
<p>You acknowledge that You have read, understood and agreed to be bound by this Agreement at all times. By executing the Form, You have also agreed and accepted to be bound by the terms and conditions incorporated in the &ldquo;FNI Code of Conduct, FNI Distributor Manual , and FNI Business Manual ", &ldquo;FNI Distributorship Opportunity" which has been accepted by You and shall be deemed to be a part of this Agreement, and in the event of any conflict between this Agreement and any aforesaid FNI Distributor Guidelines, this Agreement shall prevail. If You do not wish to adhere to the terms and conditions herein or any of the terms of the FNI Distributor Guidelines, please do not execute the Form or forthwith terminate this Agreement. It is clarified that the FNI Distributor shall exclusively market, sell and distribute only the Products of FNI, unless otherwise expressly agreed in writing by FNI.</p>
<ol>
<li>Subject to this Agreement, FNI hereby appoints the FNI Distributor and the FNI Distributor hereby accepts its appointment on a principal-to-principal, non-exclusive basis to use, promote and resell the Products in India.</li>
<li>Upon executing the Form, you agree to registering on the FNI&rsquo;s website, available at website (www.friendsnetindia.com). You get unique ID (identification number) and password to operate your Business Operation Desk. In the event of any discrepancy between the terms of this Agreement and the Website, the terms of this Agreement shall prevail. You agree that you shall not be entitled to register with more than one Account without permitted by company&rsquo;s directors and promotors on the Website for any reason whatsoever. In the event FNI has reason to believe that you or any Person on behalf of you has activated more than one Business Operation Centre (BOD), this Agreement shall forthwith be deemed to be terminated. In the event this Agreement is terminated for any reason whatsoever, the FNI Distributor shall not be eligible to apply for a position as an FNI Distributor, for a period of 6 (Six) months from the date of termination or for such period as FNI may in its sole discretion decide.</li>
<li><br /> Simultaneous to or within 15 (Fifteen) days from the date of executing the Form, You agree to submit the physical copies of the following documents(&ldquo;Registration Documents") to FNI at its registered office located at Bhopal [Mention Details in your Form] and the same shall be acknowledged byFNI in writing :-</li>
</ol>
<p><br /> (a) Original FNI Consumer Registration Form<br /> (b) One Colour Passport Size Photograph <br /> (c) A self-attested PAN card copy<br /> (d) A Self Attested Cancelled Cheque bearing Account Number &amp; IFSC code<br /> (e) A self- attested copy of the address proof - UID / Aadhar Card preferred</p>
<ol start="4">
<li>Your KYC should be submitted to head office within 15(Fifteen) days period, otherwise the Form shall be deemed to be terminated and Your Business Operation Centre shall automatically stand terminated, without any further liability on FNI. Further FNI may reject the form, in whole or part for any reason, at its discretion, including but not limited to the form containing incomplete, inaccurate, false or misleading information. Any alteration or modification of the Form will be subject to rejection. For the avoidance of doubt, this Agreement shall be effective and valid from the date of acceptance of the Form by FNI.</li>
<li>The FNI Distributor hereby confirms that he/she has entered into this Agreement as an independent Contractor. Nothing in the Agreement shall establish an employment relationship, or any other labour relationship between the FNI Distributor (s) and FNI. This is not an exclusive arrangement from FNI and FNI reserves the right to enter an arrangement similar to the arrangement contemplated under this Agreement with other Persons, at its discretion.</li>
<li>Upon any modification or alteration of the Agreement or the Form, the latest revised version of the Agreement shall be effective and binding on the FNI Business Distributors on the earlier of (a) it being reflected on the Website; or (ii) in any communication sent to the FNI Distributor by FNI. Continuation by the FNI Distributor to perform its/his/her obligations under this Agreement or non-termination of the Agreement in accordance with the process detailed here under, shall be deemed acceptance to the modified or changed Agreement or Form.</li>
<li>FNI has the right and You hereby irrevocably grant a right to FNI to conduct a background verification and/or an audit (legal, financial or otherwise) on You, Your business activities, and books of account as may be applicable, at its sole discretion, without giving any prior notice to You. Additionally, you also agree to provide FNI with a compliance certificate on a [quarterly] basis, evidencing Your compliance with applicable laws.</li>
<li>FNI shall not be responsible for the conduct of the FNI Distributor for any reason whatsoever. Additionally, FNI shall be solely responsible for any complaint, dispute, and claim regarding the Products sold by the FNI Distributor.</li>
<li>REPRESENTATIONS AND WARRANTIES OF THE FNI Distributor<br /> The FNI Distributor hereby represents and warrants that:<br /> (i) He/she/it is authorized under applicable law to enter into and execute this Agreement;<br /> (ii) He/she/it is not an existing FNI Distributor of FNI;<br /> (iii) He/she/it has not entered into an agreement with any other third party which conflicts with its obligations hereunder;<br /> (iv) He/she/it has taken and completed all statutory, legal, regulatory, corporate and other approvals as may be required for the transactions contemplated under this Agreement<br /> (v) The personal information submitted to FNI by the FNI Distributor under the Form or the Account is true and accurate to the best knowledge of the FNI Distributor<br /> (vi) He/she/it (or its directors, as may be applicable) is not part of any ending civil or criminal proceedings under any court of law; and<br /> (vii) He/she/it has read, understood and agreed to be bound by the terms and conditions of the FNI Distributor Guidelines as applicable.</li>
<li>ADDITIONAL OBLIGATIONS OF FNI<br /> The FNI Distributor hereby undertakes and declares that he/she/it shall:<br /> (i) Ensure that the FNI Distributor Guidelines are adhered to at all times;<br /> (ii) FNI shall inform FNI Distributor about new Products or Services that are competitive with FNI&rsquo;s Products &amp; Services and other market Information and competitive information as generated and collected from time to time.<br /> (iii) Ensure that the pricing of the Products are not above the maximum retail price of the relevant Product;<br /> (iv) Ensure that he/she/it does not represent the Product in any manner other than as provided in the respective Products brochure;<br /> (v) Ensure that he/she/it does not infringe the intellectual property rights of FNI ;<br /> (vi) Ensure that he/she/it does not misrepresent the benefits, side-effects, constituents or ingredients of the Products;<br /> (vii) Ensure that he/she/ it is in compliance with applicable law at all times;<br /> (viii) Ensure that the personal information provided to FNI during the validity of this Agreement and the Account is true and accurate to the best knowledge of the FNI Distributor;<br /> (ix) Ensure that he/she/it conducts him/her/itself in a workmanlike manner, without causing any harm to the reputation of FNI Distributor or its Products;<br /> (x) Shall not enter into any agreement similar to the arrangement contemplated under this Agreement with any other entity or Person during the term of this Agreement;<br /> (xi) Shall provide a compliance certificate on a quarterly basis, as may be required by FNI ;<br /> (xii) Maintain the confidentiality of the information provided by FNI at all times;<br /> (xiii) Not use market or sell the Products in any manner which may cause any adverse effect to FNI ; and<br /> (xiv) Not modify, reverse engineer or alter the Products and the intellectual property rights of FNI in any manner whatsoever.<br /> (xv) FNI shall, at its own expense, promptly provide FNI Associate and marketing and technical information, training information, training concerning the services, brochures, instructional material, advertising literature, and other product data.</li>
<li>TERMINATION AND SET-OFF<br /> (i)Upon termination of this Agreement, the Account of the FNI Distributor shall be de-activated automatically and he/she/it shall return, within a period of 30 (Thirty ) days from the date of termination, the marketing material, confidential information of FNI , including any copies thereof, and shall immediately stop using the trademarks, trade names, brand names, service marks or logos of FNI for the promotion and sale of the Products.<br /> Upon termination of this Agreement, in the event that You have not paid any sum or sums which are due and payable to FNI , either in the capacity of a FNI Distributor or otherwise, FNI shall have the right at its sole discretion to reduce your indebtedness by setting off against each indebtedness any sums due and payable to you by FNI or any of its affiliates.</li>
<li>PAYMENT<br /> (a) All payments as applicable must be made by demand draft in favor of us. M/s FNIONLINE MARKETING PRIVATE LIMITED., payable at DHANBAD, JHARKHAND. Cash payments may only be accepted at the corporate office of FNI and other offices (Branches designated time to time, Additionally payment will also be accepted through normal banking channels).<br /> (b) The pay-outs to the FNI Distributor shall be as per the 'FNI Distributorship Opportunity ". The co-applicant acknowledges and agrees that FNI shall deal exclusively with the primary applicant in respect to all business matters and also pay the pay-outs and/or any other incentives to and in the name of the primary applicant. The FNI Distributor shall directly comply with the confidentiality obligations provided under the Procedural Guidelines of FNI. Any incentives indicated as payable/paid to the FNI Distributor by FNI under the Business Plan is inclusive of all service tax and other taxes/levies on the transaction. The FNI Distributor must make requisite arrangements to pay all applicable taxes. FNI shall be entitled to deduct tax deducted at source, at applicable rates from time to time.</li>
</ol>
<p>13 PRICING AND AVAILABILITY<br /> 13.1 FNI reserves the right, at its discretion, to change the prices and availability of the Products without prior notice. The price of each Product represents the full retail price of the Product, reflected in Indian National Rupees, as per standard industry practice and is inclusive of all applicable charges, cess, levies and taxes, unless specified otherwise.<br /> 13.2 FNI has taken due care to ensure accurate Product and pricing information. In the event there is any error in the pricing of the Product or typographical error on the availability and Product information, FNI shall have the right, at its discretion, to either contact you for instructions or cancel your order and notify you of such cancellation.</p>
<ol start="14">
<li>MARKETING AND USE OF BRAND NAME<br /> 14.1 The FNI Distributor shall, at its own cost and expense, carry out marketing and promotional activities as may be required for the purpose of sale of the Products, subject to such FNI Distributor following the FNI MULTIVENTURES PRIVATE LIMITED Guidelines. For the avoidance of doubt, it is clarified that no marketing material may be used or created by the FNI Distributor for marketing, displaying of selling the Products without the prior written approval of FNI.<br /> 14.2 FNI hereby grants the FNI Distributor a limited, royalty-free, non-exclusive, non-transferable, revocable right or license to use FNI's trademarks, trade names, brand names, service marks or logos solely for the use of the same in marketing the Products, during the term of this Agreement.</li>
<li>INTELLECTUAL PROPERTY<br /> 15.1 The FNI Distributor acknowledges that the intellectual property rights with respect to the Products will remain the exclusive property of FNI. Neither the FNI Distributor nor any of its representatives or agents shall alter or copy the design of the Products, trademark, trade name or other proprietary notices, symbols, marks or labels appearing on the Products or otherwise infringe the intellectual property rights of FNI. This Agreement does not grant or assure any right of ownership in the products to the FNI Distributor. The FNI Distributor hereby acknowledges it will not remove any copyright or other proprietary rights notices contained in the products or marketing material provided to it by FNI and shall not make application to any authorities for registration of any intellectual property rights for any work created using the logo of FNI or any other property belonging to FNI. No rights in the products are granted to the FNI Distributor except the limited license contained in this Agreement. Any right, title or interest arising in any compilation or derivative work created using the intellectual property rights of FNI shall not entitle the FNI Distributor to use such intellectual property rights, except as specifically permitted hereunder. All rights in such derivative or compilation work created by FNI Distributor using the intellectual property rights of FNI shall vest entirely with FNI.<br /> 15.2 The FNI Distributor agrees to promptly notify FNI in writing upon its discovery of any unauthorized use or infringement or potential infringement of the intellectual property rights in the products by any third party.</li>
</ol>
<p>16 .INDEMNITY<br /> The FNI Distributor hereby indemnifies and agrees to keep indemnified and harmless FNI, its officers, employees, directors, shareholders, customers and agents from and against any and all claims, damages, costs, expenses, including attorney's fees, arising out of or in connection with (i) breach of representations warranties and covenants under this Agreement; (ii) breach of applicable law; (iii) use/misuse/infringement of the intellectual property rights of FNI ; and (iv) non-compliance with the FNI Distributor Guidelines and the FNI Distributorship Opportunity. The FNI Distributor shall pay the indemnity amount to FNI within 14 days from the date of request.</p>
<ol start="17">
<li>LIMITATION OF LIABILITY<br /> FNI does not provide a warranty, implied or otherwise, on the products to be purchased by the FNI Distributor and shell not be liable for the products in any manner whatsoever. Notwithstanding anything to the contrary contained in this Agreement or the Form, in no event shall FNI be liable to you or any other party seeking damages under this Agreement or the Form, whether in contract, tort (including negligence) or otherwise, for any special, indirect, incidental, punitive or consequential losses, damages, costs or expenses whatsoever, including without limitation damages related to loss of profits or of contracts, losses of business or of revenues, losses of operation time or goodwill or reputation. FNI&rsquo;s aggregate liability under or in connection with this Agreement or the Form (whether in contract, tort including negligence or other-wise), shall in no event exceed the incentive paid to the FNI Distributor by FNI in the immediately preceding 2 (Two) months, from the date the claim arises.</li>
<li>NOTICE<br /> All notices, requests and other communications under this Agreement shall be in writing, in English or Hindi. Any notice or information/document or communication to be served under this Agreement may be served upon either party hereto only by email or courier or posting by registered post or delivering by hand or through facsimile transmission. The notice or demand to be served on the party should be served at its address, facsimile number mentioned in the Form.</li>
</ol>
<p>19.GOVERNING LAW AND JURISDICTION<br /> 19.1 This Agreement shall, in all respects be governed by and construed in accordance with the laws of India and subject to Clause 20 below, the courts at Dhanbad shall have the sole and exclusive jurisdiction to entertain any disputes that may arise hereunder.<br /> 19.2 The parties here to undertake to use their best efforts to resolve amicably any dispute arising out of or in connection with this Agreement or the Form and the interpretation thereof through consultation in good faith and mutual understanding, provided that such consultation shall not prejudice the exercise of any right or remedy of either party hereto by any such party in respect of any such dispute.<br /> 20. ARBITRATION<br /> 20.1 In the event the parties hereunder are unable to resolve a dispute through amicable settlement pursuant to Clause 19 above within 15 (fifteen) days from the date a party raises a dispute, the dispute shall be submitted to final and binding arbitration at the request of either of the parties upon written notice to that effect to the other.<br /> 20.2 Such arbitration shall be in accordance with the Arbitration and Conciliation Act, 1996 and shall be held at Bhopal. All proceedings of such arbitration shall be in the English or Hindi language. The arbitration shall be conducted by a sole arbitrator to be appointed in accordance with the provisions of the Arbitration and Conciliation Act, 1996. If the parties are unable to mutually agree upon the sole arbitrator within 30 (thirty) days from the date of request for arbitration by either party, the arbitration panel shall consist of 03 (three) arbitrators, with FNI and the FNI Distributor empowered to appoint one arbitrator each and the third arbitrator shall be appointed by two of the other arbitrators.</p>
<ol start="21">
<li>FORCE MAJEURE<br /> If FNI's performance or any of its obligations hereunder is prevented, restricted or interfered with by reason of fire, flood or other casualty, accident, illness, strike or labour disputes, war or other violence, any law or regulation of any Government, or any act or condition whatsoever beyond its reasonable control (each such occurrence being hereinafter referred to as (Force Majeure Event'), then FNI shall be excused from such performance to the extent of such prevention, restriction and interference. Payment obligations of the FNI Distributor to FNI under this Agreement shall not be subject to this Clause 21.</li>
<li>SEVERABILITY<br /> In case any one or more of the provisions contained in this Agreement or the Form shall, for any reason, be held to be invalid, illegal or unenforceable in any respect, such invalidity, illegality or unenforceability shall not affect the other provisions of this Agreement or the Form, and relevant provisions shall be construed as if such invalid, illegal or unenforceable provision had never been contained herein. Any invalid or unenforceable provision of this Agreement or the Form shall be replaced with a provision, which is valid and enforceable and most nearly reflects the original intent of the unenforceable provision.</li>
<li>CONFIDENTIALITY AND NON-DISCLOSURE<br /> 23.1 The FNI Distributor shall during the term of this Agreement and thereafter keep all information and other materials exchanged with FNI in relation to the transactions contemplated by this Agreement confidential (including all information concerning the business transactions, business model, client, marketing material, Product details/information, customers, prospective customers and the financial arrangements relating FNI), which was either designated as confidential or which was by its nature, confidential (the &ldquo;Confidential Information&rdquo;), and shall not without the prior written consent of FNI divulge such information to any other person or use such Confidential Information other than for carrying out the purposes of this Agreement.</li>
</ol>
<p>23.2 For the purposes of this Agreement, Confidential Information shall not include:<br /> ( a ) information that is in the public domain as on the data of this Agreement;<br /> ( b) information that is generally available to the public otherwise than as a breach of this Agreement; and</p>
<p>&copy; Information that the FNI Distributor is under an obligation to disclose, pursuant to any applicable law. However, the FNI Distributor shall provide sufficient documentary evidence to the Company regarding the specific requirement under the applicable law.<br /> 23.3 No announcements or other disclosures concerning the transactions forming the subject matter of this Agreement or any terms and conditions hereof shall be made by the FNI Distributor, without agreed by FNI in writing.</p>
    <!-- Register -->
    <p>Not a member?
        <a href="/registration">Register</a>
    </p>

    

<!-- Default form login -->
</div>
</div>
</div>

</div>

      </section>
    </div>
</main>  